      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_key: ${{ env.SA }}
          project_id: ${{ env.PROJECT_ID }}
      - run: |
          gcloud builds submit \
              --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_RUN_NUMBER --verbosity=debug
      - run: |
          gcloud run deploy $BRANCH_NAME-$REPO_NAME \
          --quiet \
          --region $RUN_REGION \
          --image gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_RUN_NUMBER \
          --platform managed \
          --allow-unauthenticated
