name: Artisan Playground [staging]
on:
  push:
    branches: [staging]
env:
  PROJECT_ID: artisan-playground
  RUN_REGION: asia-southeast1
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_OWNER: ${{ github.event.repository.owner.login }}
  SA: ${{ secrets.SA_ARTISAN_PLAYGROUND }}
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_key: ${{ env.SA }}
          project_id: ${{ env.PROJECT_ID }}
      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "::set-output name=dir::$(yarn cache dir)"
      - run: ./build.sh react-app
      - run: gcloud auth configure-docker
      - name: Local Build
        run: docker build -t "gcr.io/$PROJECT_ID/$REPO_NAME:${GITHUB_RUN_NUMBER}" .
      - run: docker push "gcr.io/$PROJECT_ID/$REPO_NAME:${GITHUB_RUN_NUMBER}"
      # - run: |
      #     gcloud builds submit \
      #         --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_RUN_NUMBER --verbosity=debug
      - run: |
          gcloud run deploy $BRANCH_NAME-$REPO_NAME \
          --quiet \
          --region $RUN_REGION \
          --image gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_RUN_NUMBER \
          --platform managed \
          --allow-unauthenticated
      - run: |
          # docker build -t
      - run: |
          echo "hello world :)"
